apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kafkop
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafkop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-20.0.1
  name: kafkop-kafka-external
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-client
    port: 9092
    protocol: TCP
    targetPort: kafka-client
  - name: tcp-internal
    port: 9093
    nodePort: 9093
    protocol: TCP
    targetPort: kafka-internal
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafkop
    app.kubernetes.io/name: kafka
  sessionAffinity: None
  type: NodePort
