---
- import_playbook: common-playbook.yml
- hosts: all
  become: true
  tasks:

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --node-name {{ node_name }} --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.10

    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config

    - name: Install calico networking
      become: false
      command: kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

    - name: Fetch kubeconfig to local
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: kubeconfig
        flat: yes
